;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	neotree-toggle
	))

(setq mc/cmds-to-run-once
      '(
	ergoemacs-undo
	mouse-set-region
	))
